dirs:
  data_dir: data
  train_dir: train
  test_dir: test
  image_dir: images
  mask_dir: masks
  model_dir: models
  output_dir: output
  pred_mask_dir: predicted_masks
  pred_plot_dir: prediction_plots
  log_dir: logs
vars:
  train_log_name: train.log
  test_log_name: test.log
  log_level: 'DEBUG'
  patch_size: 512
  batch_size: 16
  model_name: trained_landcover_unet_efficientnet-b0_epochs18_patch512_batch16.pth
  encoder: 'efficientnet-b0'
  encoder_weights: 'imagenet'
  activation: 'softmax2d'
  epochs: 20
  train_classes: ['background', 'building', 'woodland', 'water']  # not training on 'road' class since it's instances in the data is too less
  test_classes: ['background', 'building', 'water']  # the class prompt - edit according to what you want to have in the output masks
  device: 'cpu'  # 'cpu' or 'cuda' - edit according to your device